// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class validationforcustomername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validationforcustomername));
        
        string IMigrationMetadata.Id
        {
            get { return "201810131635452_validation-for-customer-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
